"""empty message

Revision ID: 00d045eb99d5
Revises: 4addcf192f49
Create Date: 2023-04-19 09:55:41.383023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d045eb99d5'
down_revision = '4addcf192f49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
