"""update

Revision ID: 01f610160ff2
Revises: 4489ab33bada
Create Date: 2023-05-01 23:31:00.430567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f610160ff2'
down_revision = '4489ab33bada'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
