"""update

Revision ID: 02325c8178c6
Revises: 03389718f4c7
Create Date: 2023-05-02 16:28:03.135543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "02325c8178c6"
down_revision = "03389718f4c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
