"""update

Revision ID: 03389718f4c7
Revises: 01f610160ff2
Create Date: 2023-05-01 23:45:22.706907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03389718f4c7'
down_revision = '01f610160ff2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
