"""empty message

Revision ID: b96e5c319ebf
Revises: 8a862d54bbb4
Create Date: 2023-04-25 11:13:06.653585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b96e5c319ebf"
down_revision = "8a862d54bbb4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_user_email"), ["email"])
        batch_op.create_unique_constraint(batch_op.f("uq_user_username"), ["username"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_user_username"), type_="unique")
        batch_op.drop_constraint(batch_op.f("uq_user_email"), type_="unique")

    # ### end Alembic commands ###
